name: ESP32 Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ESP-IDF
        uses: espressif/setup-esp-idf@v2
        with:
          version: 'v5.1'

      - name: Build Project
        run: idf.py build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/
