name: Docker ESP32 Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with Docker
        run: |
          docker build -t esp32s3-build .
          docker run --rm -v ${{ github.workspace }}:/project esp32s3-build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
